version: "2.4.1"

services:
  web1:
    image: reimbursement-api:version2
    container_name: rApp
    restart: always
    environment:
      - DB_URL=jdbc:mysql://34.68.5.194:3306/ers
    ports:
      - 8080:8080
    depends_on:
      - db

  web2:
    image: email-api:version2
    container_name: eApp
    restart: always
    environment:
      - DB_URL=jdbc:mysql://34.68.5.194:3306/ers
    ports:
      - 8089:8089
    depends_on:
      - db

  db:
    image: mysql
    container_name: db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=ers
      - MYSQL_ROOT_USER=root
